In [2]:
import pandas as pd
from sqlalchemy import create_engine, text
import logging

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def create_cleaned_table(engine):
    try:
        # Create new table with nulls converted to 0
        query = """
        CREATE TABLE dbo.gas_automated_meter_cleaned AS
        SELECT 
            meter_description,
            COALESCE("Jan_2022", 0)::float as Jan_2022,
            COALESCE("Feb_2022", 0)::float as Feb_2022,
            COALESCE("Mar_2022", 0)::float as Mar_2022,
            COALESCE("Apr_2022", 0)::float as Apr_2022,
            COALESCE("May_2022", 0)::float as May_2022,
            COALESCE("Jun_2022", 0)::float as Jun_2022,
            COALESCE("Jul_2022", 0)::float as Jul_2022,
            COALESCE("Aug_2022", 0)::float as Aug_2022,
            COALESCE("Sep_2022", 0)::float as Sep_2022,
            COALESCE("Oct_2022", 0)::float as Oct_2022,
            COALESCE("Nov_2022", 0)::float as Nov_2022,
            COALESCE("Dec_2022", 0)::float as Dec_2022,
            COALESCE("Jan_2023", 0)::float as Jan_2023,
            COALESCE("Feb_2023", 0)::float as Feb_2023,
            COALESCE("Mar_2023", 0)::float as Mar_2023,
            COALESCE("Apr_2023", 0)::float as Apr_2023,
            COALESCE("May_2023", 0)::float as May_2023,
            COALESCE("Jun_2023", 0)::float as Jun_2023,
            COALESCE("Jul_2023", 0)::float as Jul_2023,
            COALESCE("Aug_2023", 0)::float as Aug_2023,
            COALESCE("Sep_2023", 0)::float as Sep_2023,
            COALESCE("Oct_2023", 0)::float as Oct_2023,
            COALESCE("Nov_2023", 0)::float as Nov_2023,
            COALESCE("Dec_2023", 0)::float as Dec_2023,
            COALESCE("Jan_2024", 0)::float as Jan_2024,
            COALESCE("Feb_2024", 0)::float as Feb_2024,
            COALESCE("Mar_2024", 0)::float as Mar_2024,
            COALESCE("Apr_2024", 0)::float as Apr_2024,
            COALESCE("May_2024", 0)::float as May_2024,
            COALESCE("Jun_2024", 0)::float as Jun_2024,
            COALESCE("Jul_2024", 0)::float as Jul_2024,
            COALESCE("Aug_2024", 0)::float as Aug_2024,
            COALESCE("Sep_2024", 0)::float as Sep_2024,
            COALESCE("Oct_2024", 0)::float as Oct_2024,
            COALESCE("Nov_2024", 0)::float as Nov_2024
        FROM dbo.gas_automated_meter;
        """
        with engine.connect() as conn:
            # Drop table if exists
            conn.execute(text("DROP TABLE IF EXISTS dbo.gas_automated_meter_cleaned"))
            conn.execute(text(query))
            conn.commit()
            
        logger.info("Created cleaned table with nulls converted to 0")
        
    except Exception as e:
        logger.error(f"Error creating cleaned table: {e}")
        raise

def main():
    try:
        # Database connection parameters
        db_params = {
            'host': 'localhost',
            'database': 'uems_db',
            'user': 'admin_uems',
            'password': 'uems2025',
            'port': 5432
        }
        
        # Create database connection
        db_url = f"postgresql://{db_params['user']}:{db_params['password']}@{db_params['host']}:{db_params['port']}/{db_params['database']}"
        engine = create_engine(db_url)
        
        # Create cleaned table
        create_cleaned_table(engine)
        
    except Exception as e:
        logger.error(f"Main execution failed: {e}")
        raise

if __name__ == "__main__":
    main()

INFO:__main__:Created cleaned table with nulls converted to 0